//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeMotors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobil
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public int MotorTypeId { get; set; }
        public Nullable<decimal> Motor { get; set; }
        public Nullable<int> TransmissionId { get; set; }
        public string Color { get; set; }
        public Nullable<int> Millage_km_ { get; set; }
        public Nullable<int> ModelId { get; set; }
    
        public virtual MotorType MotorType { get; set; }
        public virtual Transmission Transmission { get; set; }
        public virtual Model Model { get; set; }
    }
}
